[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "letterboxdpy"
version = "4.5"
authors = [
  { name="Nicholas Cassarino", email="nmcassa804@outlook.com" },
]
description = "A letterboxd webscraper"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "requests==2.31.0",
    "beautifulsoup4==4.12.3",
    "lxml==5.1.0"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/nmcassa/letterboxdpy"
"Bug Tracker" = "https://github.com/nmcassa/letterboxdpy/issues"

[tool.hatch.build.targets.wheel]
packages = ["letterboxdpy"]
